apiVersion: v1
kind: Secret
metadata:
  name: {{ include "up42-app.shared-minio-password" . }}
  labels:
    app: {{ include "up42-app.name" . }}
type: Opaque
data:
  password: {{ randAlphaNum 12 | b64enc }}
  username: {{ .Values.minio.username | b64enc }}

