apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.service.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "up42-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.service.port }}
      protocol: TCP
      name: minio-api-port
  selector:
    {{- include "up42-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
