{{- if .Values.minio.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: minio-hpa
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "up42-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "up42-app.fullname" . }}-minio
  minReplicas: {{ .Values.minio.hpa.minReplicas }}
  maxReplicas: {{ .Values.minio.hpa.maxReplicas }}
  metrics:
    {{- if .Values.minio.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.minio.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.minio.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.minio.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
