{{- if .Values.minio.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio-pdb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "up42-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.minio.pdb.minAvailable }}
  minAvailable: {{ .Values.minio.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.minio.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.minio.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "up42-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
{{- end }}
