{{- if .Values.s3www.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: s3www-hpa
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "up42-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "up42-app.fullname" . }}-s3www
  minReplicas: {{ .Values.s3www.hpa.minReplicas }}
  maxReplicas: {{ .Values.s3www.hpa.maxReplicas }}
  metrics:
    {{- if .Values.s3www.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.s3www.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.s3www.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.s3www.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
