apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.s3www.service.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "up42-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3www
spec:
  type: {{ .Values.s3www.service.type }}
  ports:
    - port: {{ .Values.s3www.service.port }}
      targetPort: {{ .Values.s3www.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "up42-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: s3www
